### ISSUE TITLE
[docs] Add info about tile coordinates

### ISSUE THREAD

**Issue by rmglennon** [tilezen/joerd#109]
A support ticket came in where the user was trying to get a tile by passing decimal degrees, instead of tile coordinates.

We should clarify that the the {x}/{y} is a tile coordinate. Currently, it looks pretty much the same as the standard decimal degrees format. Need to tell people that tile coordinates are used and provide instructions for teaching people how to convert

@kkowalsky knows of some resources that we can add to docs.

**Comment by nvkelso** [comment]
We should make the same change in the vector tile documentation.

**Comment by kkowalsky** [comment]
💪

**Comment by mikejeffe** [comment]
thanks. I was pulling the coords from id editor in osm thinking they would be the same.  I appreciate the clarification!

**Comment by nvkelso** [comment]
Thanks, @wafflebot[bot].
