### ISSUE TITLE
[docs] Clarify required Mapzen attribution for service

### ISSUE THREAD

**Issue by nvkelso** [tilezen/joerd#112]
Reading the terrain tile docs for [attribution](https://mapzen.com/documentation/terrain-tiles/attribution/) it seems like I would only needs to attribute `U.S. Geological Survey` and `U.S. National Oceanic and Atmospheric Administration`, but when using the hosted service (which most anyone is), a developer would also be required to credit Mapzen (see [terms of use](https://mapzen.com/documentation/overview/#terms-of-use)).

We should update the vector tile attribution page to make this clearer.

The required attribution could probably be simplified to:

**Mapzen's hosted service:**

`Mapzen, U.S. Geological Survey, and U.S. National Oceanic and Atmospheric Administration.`
or
`Mapzen, USGS, and NOAA.`

**Self-hosted:**

`U.S. Geological Survey, and U.S. National Oceanic and Atmospheric Administration.`
or
`USGS, and NOAA.`

Related: https://github.com/tilezen/vector-datasource/issues/1113

**Comment by kkowalsky** [comment]
will work on this for the next docs release
