### ISSUE TITLE
[docs] add api key samples

### ISSUE THREAD

**Issue by kkowalsky** [tilezen/joerd#122]
like: https://github.com/tilezen/vector-datasource/issues/1155

it can be confusing to know how to add an API key to the end of a query and so we should add samples in the docs (at least in 'get started') like api_key=mapzen-xxxxxx in case the link to mapzen.com/documentation/overview isn't obvious.

**Comment by nvkelso** [comment]
I dig mostly reverting https://github.com/tilezen/joerd/commit/73958bd88104b7d62cef7d5b6cd048338736c85f#diff-855958b9614db5d6630b10c60ab35e42 ;)

**Comment by kkowalsky** [comment]
oy
