### ISSUE TITLE
vertical datum?

### ISSUE THREAD

**Issue by DarkForceOne** [tilezen/joerd#130]
What is the vertical datum of the elevation data?

**Comment by zerebubuth** [comment]
It should be the WGS84 nominal sea level, but there may be deviations from that depending on which dataset provided the samples in question. Does that help?

**Comment by DarkForceOne** [comment]
Yes, it does answer my question. 

I have seen some projects related to seawater intrusion where a few feet (decimeters) is critical. Since we often compare elevation data from different sources, a standardized vertical datum would allow users to convert the data to the same standard before comparing them. 

It would be great to clearly define and use a standardized vertical datum. Many thanks!
