### ISSUE TITLE
Serving normal tiles for Walkabout

### ISSUE THREAD

**Issue by rwrx** [tilezen/joerd#153]
Could Joerd be used as tile server serving normal tiles for Walkabout style? It there some tutorial about how to run it and serve tiles on local machine? Thank you.

**Comment by nvkelso** [comment]
Joerd is for creating tile assets, not really serving them up. We've moved over to https://github.com/mojodna/marblecutter/ to support terrain tiles. It does support running and serving tiles in addition to making the tiles.

But if you're just looking to bundle up normal tiles for Walkabout you can scape them (they're all pre-generated).

- https://mapzen.com/documentation/terrain-tiles/use-service/
- S3 endpoints are covered: https://mapzen.com/documentation/terrain-tiles/use-service/#additional-amazon-s3-endpoints

So combined with the change you made over in tilepacks, you could point at the S3 bucket directly:

- https://github.com/tilezen/tilepacks/pull/7

Is there a preview available for the app you're building?

**Comment by rwrx** [comment]
Thank you. So could I point to that S3 endpoints? These are not paid? Because in that path patterns I don't see Mapzen API key parameter. 

Currently I have only free version of my app released on Google Play Store: https://play.google.com/store/apps/details?id=com.vecturagames.android.app.gpxviewer . I am going to release paid PRO version of my app with offline maps in August. So I am a little bit in hurry :).

**Comment by nvkelso** [comment]
That's correct, the S3 buckets are a partnership with Amazon via their public datasets program.
