### ISSUE TITLE
Utility of combined elevation/bathymetry HGT files?

### ISSUE THREAD

**Issue by XPav** [tilezen/joerd#172]
I'm having a hard time figuring out what the combination of the elevation data and bathymetry data does, or more specifically, why these data are combined into a single dataset.   

With the HGT files, one is unable to tell distinguish whether a specific location has an elevation below sea level, or is covered with water, so I've got to specifically check for the locations on earth that have negative elevation?

Thanks

**Comment by nvkelso** [comment]
Generally one does that check with a water mask layer. SRTM provides one, or you can use the OSM water/land polygons (both vectors, but can be rasterized at same resolution as terrain data).

**Comment by XPav** [comment]
Perfect, thanks for the tips.
