### ISSUE TITLE
AWS Tile Resolution

### ISSUE THREAD

**Issue by japauljr** [tilezen/joerd#177]
After sampling the AWS public dataset skadi files, it appears that the resolution is 30m.   Is there a source that is 10m or better?

**Comment by mojodna** [comment]
Skadi will always be 30m, since they're effectively SRTM HGT files (the format supports only 30m and 15m data).

All of the other formats will have better resolution (but not everywhere, depending on underlying source availability).

**Comment by nvkelso** [comment]
The documentation shows where the resolution is better as image and as geojson coverage file.
