### ISSUE TITLE
GeoTiff Files

### ISSUE THREAD

**Issue by japauljr** [tilezen/joerd#179]
I am using a legacy DEM service that is based on WGS84/EPSG:4326 Ascii GRID.   I see that the GeoTiff files are on EPSG:3857.   If I wanted obtain the best resolution files available from the world sources: 

1. Does zoom level-15 contain the entire world just at different resolutions(1m, 3m, 10m, 30m) based on source(ned,gmted,srtm,etc)?

2. What is the appropriate GDAL_Translate command for converting the geotiff files to WGS84/EPSG:4326 AAIGRID format?

**Comment by nvkelso** [comment]
1. Zoom 15 does contain the entire world at a set resolution but the source data for that zoom varies (some is 1m, some 10m, some 30m, some 1000m). See https://mapzen.com/documentation/terrain-tiles/data-sources/.

2. StackExchange is usually a good place to look for format translation help. I see https://gis.stackexchange.com/questions/77917/converting-gtiff-to-ascii-grid-using-qgis-gdal-translate.
