### ISSUE TITLE
Terrain Data

### ISSUE THREAD

**Issue by japauljr** [tilezen/joerd#180]
In the documentation:  https://mapzen.com/documentation/terrain-tiles/data-sources/#known-issues,  It is not uncommon to see large variations in elevation in areas with large buildings and other such structures.

Is the GTiff data DSM: Digital Surface Model or DTM: Digital Terrain Model?

**Comment by mojodna** [comment]
It's intended as a digital terrain model, and all selections of sources have taken that into account, but that's definitely not a guarantee that artifacts aren't present.

**Comment by nvkelso** [comment]
Yep, GTM is the same-ish as DEM.
