### ISSUE TITLE
Availability of dataset

### ISSUE THREAD

**Issue by RobertMouncer** [tilezen/joerd#187]
Is the terrain tiles dataset available to all for free?
I struggle to follow the license from mapzen considering they have stopped trading.

**Comment by iandees** [comment]
You can access the terrain tiles data via AWS directly. More information is available here: https://github.com/tilezen/joerd/blob/master/docs/use-service.md#additional-amazon-s3-endpoints. More information is here, too: https://registry.opendata.aws/terrain-tiles/

You can also use Nextzen, a continuation of the Mapzen tile services: https://developers.nextzen.org/about.html
