### ISSUE TITLE
Hosting of 260px tiles (with overlapping) on aws?

### ISSUE THREAD

**Issue by molzer** [tilezen/joerd#198]
I recently found the 260px tiles on https://tile.mapzen.com/mapzen/terrain/v1/260/
Until now, I got tiles from the aws S3 bucket via https://s3.amazonaws.com/elevation-tiles-prod/terrarium/ which was super reliable and fast (and free). However, my 3D application strongly benefits from the 260px tiles (with overlap buffer).

I have two questions:
1. Are there any plans to make them available with aws S3 as well?

2. https://www.mapzen.com/blog/512-pixel-tiles-and-basemaps/ says that 
> Access to Mapzen’s terrain tiles continue to be free (with an API key) – they are not billed in Mapzen Flex.

Which is great! However, is server performance/reliability provided by tile.mapzen.com comparable to s3.amazonaws.com? Or is its foundation s3 anyways? What's the best way for me to retrieve the 260px tiles?

**Comment by nvkelso** [comment]
On nextzen.org we run https://github.com/tilezen/zaloa to merge together the tiles for buffered output.
