### ISSUE TITLE
What vertical reference is used in the tile data?

### ISSUE THREAD

**Issue by jbroll** [tilezen/joerd#205]
It seems like the vertical reference system is not documented anywhere I've looked.  It is EMG96?, WGS84 ellipsoid?  Does the documentation clearly state this somewhere?  Thanks!

**Comment by nvkelso** [comment]
Generally we assume WGS84 in data sources, or try to transform into WGS84 on ingest. But we haven't performed a full audit. Is there an geographic area or tile where you think there is a problem?

**Comment by jbroll** [comment]
I'm trying to understand how to convert the data to being ellipsoid referenced for a specific application.  I understand how to do this but not what the height reference is for the tiles.  Does WGS84 mean that it is referenced to EGM2008?

**Comment by nvkelso** [comment]
There is math documented on how to make the transformations, but that's out of scope for this project. WGS84 generally refers only to the XY coordinates, while EGM2008 also considers Z (height) and change over time because the planet is still shifting around.

**Comment by jbroll** [comment]
I'm not asking for help with the math.  Do you know what the data in the tiles is referenced to?

**Comment by pchilds** [comment]
Why is this closed without an answer or update to the documentation? Is the final answer that they are all referenced to the spheroid then?
