### ISSUE TITLE
CORS expose x-amz-meta-x-imagery-sources header

### ISSUE THREAD

**Issue by hungerburg** [tilezen/joerd#213]
The aws server sends the x-amz-meta-x-imagery-sources HTTP header to tell the original source of the data. It should be exposed from the [CORS configuration](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/cors.html), so scripts from a different origin can get at it. Lacking this permission it will remain hidden from many if not most or all consumers, which kind of defeats the purpose, doesn't it?

**Comment by iandees** [comment]
The purpose of those headers was really for internal use only, but modifying the CORS configuration is pretty easy so I just did it. Please let me know if that helps.

**Comment by hungerburg** [comment]
Great! I can see response headers in developer tools and script fetched content - now tile users have no more apologies to not attribute sources ;)

(PS: I am not going to molest people, its already good, the curious get to see what is under the hood.)

**Comment by nvkelso** [comment]
+1 to attribution, nicely played
