### ISSUE TITLE
Missing tiles in Canada

### ISSUE THREAD

**Issue by nvkelso** [tilezen/joerd#86]
Developer report of missing tiles in Canada, I think in the Quebec region. 

![screen shot 2016-07-19 at 08 55 24](https://cloud.githubusercontent.com/assets/853051/17063067/6df4e734-4fea-11e6-8ec3-cb5a5c95a997.png)

**Comment by zerebubuth** [comment]
There aren't any zoom 16 tiles in Joerd, I'm afraid :disappointed:

**Comment by rmarianski** [comment]
The z15 tiles can be [overzoomed](https://mapzen.com/documentation/tangram/sources/#max_zoom).

**Comment by nvkelso** [comment]
Thanks! I've followed up with the developer.
