### ISSUE TITLE
Write GDAL example for docs

### ISSUE THREAD

**Issue by migurski** [tilezen/joerd#89]
To add to the [`nvkelso/add-docs` branch](https://github.com/tilezen/joerd/tree/nvkelso/add-docs), create a `collect.py` script to download an area of tiles, and show a GDAL command line example to sew them together into a larger GeoTIFF.

Can someone assign this to me?

**Comment by nvkelso** [comment]
The URL paths in the docs PR is future oriented, the current endpoint is:

* http://terrain-preview.mapzen.com/geotiff/{z}/{x}/{y}.tiff

They are also 512 x 512 tiles with internal 256x256 pyramiding, so you'll generally need to request the parent tile `{z-1}` and get the quadrant you're looking for from your original `z` zoom.

Example tile:

* http://terrain-preview.mapzen.com/geotiff/0/0/0.tiff

NOTE: Once the tile endpoints are rearranged, I'll update the script in a separate issue to use the new endpoint. (Please write the script based on the above examples.)

**Comment by migurski** [comment]
Noting that `.tif` is the correct filename extension.

**Comment by nvkelso** [comment]
Fixed via #90.
